import type { Reservation, Pax, ReservationDetail } from "./types"

// Mock passengers
export const mockPassengers: Pax[] = [
  {
    id: "pax-1",
    name: "María González",
    birthDate: "1985-03-15",
    nationality: "Argentina",
    dni: { dniNum: "35123456", expirationDate: "2030-03-15" },
  },
  {
    id: "pax-2",
    name: "Juan Pérez",
    birthDate: "1990-07-22",
    nationality: "Argentina",
    passport: { passportNum: "AAA123456", expirationDate: "2028-07-22" },
  },
  {
    id: "pax-3",
    name: "Laura Martínez",
    birthDate: "1978-11-30",
    nationality: "Uruguay",
    passport: { passportNum: "UY987654", expirationDate: "2027-11-30" },
  },
  {
    id: "pax-4",
    name: "Carlos Rodríguez",
    birthDate: "1995-05-10",
    nationality: "Chile",
    passport: { passportNum: "CL456789", expirationDate: "2029-05-10" },
  },
]

// Mock reservations
export const mockReservations: Reservation[] = [
  {
    id: "RSV-001",
    userId: "user-1",
    state: "CONFIRMED",
    createdAt: "2025-03-01T10:30:00Z",
    updatedAt: "2025-03-02T14:20:00Z",
    createdBy: "admin@solymar.com",
    updatedBy: "admin@solymar.com",
    currencyTotals: [
      { currency: "USD", totalPrice: 2500, amountPaid: 2500 },
      { currency: "ARS", totalPrice: 150000, amountPaid: 150000 },
    ],
    paxReservations: [{ pax: mockPassengers[0] }, { pax: mockPassengers[1] }],
  },
  {
    id: "RSV-002",
    userId: "user-2",
    state: "PENDING",
    createdAt: "2025-03-05T09:15:00Z",
    updatedAt: "2025-03-05T09:15:00Z",
    createdBy: "admin@solymar.com",
    updatedBy: "admin@solymar.com",
    currencyTotals: [{ currency: "USD", totalPrice: 1800, amountPaid: 900 }],
    paxReservations: [{ pax: mockPassengers[2] }],
  },
  {
    id: "RSV-003",
    userId: "user-3",
    state: "CONFIRMED",
    createdAt: "2025-02-28T16:45:00Z",
    updatedAt: "2025-03-01T11:30:00Z",
    createdBy: "admin@solymar.com",
    updatedBy: "admin@solymar.com",
    currencyTotals: [{ currency: "ARS", totalPrice: 450000, amountPaid: 450000 }],
    paxReservations: [{ pax: mockPassengers[3] }],
  },
  {
    id: "RSV-004",
    userId: "user-4",
    state: "CANCELLED",
    createdAt: "2025-02-20T13:20:00Z",
    updatedAt: "2025-02-25T10:00:00Z",
    createdBy: "admin@solymar.com",
    updatedBy: "admin@solymar.com",
    currencyTotals: [{ currency: "USD", totalPrice: 3200, amountPaid: 1600 }],
    paxReservations: [{ pax: mockPassengers[0] }, { pax: mockPassengers[2] }],
  },
  {
    id: "RSV-005",
    userId: "user-5",
    state: "PENDING",
    createdAt: "2025-03-08T11:00:00Z",
    updatedAt: "2025-03-08T11:00:00Z",
    createdBy: "admin@solymar.com",
    updatedBy: "admin@solymar.com",
    currencyTotals: [
      { currency: "USD", totalPrice: 4500, amountPaid: 0 },
      { currency: "ARS", totalPrice: 200000, amountPaid: 100000 },
    ],
    paxReservations: [{ pax: mockPassengers[1] }, { pax: mockPassengers[3] }],
  },
]

// Mock reservation details
export const mockReservationDetails: Record<string, ReservationDetail> = {
  "RSV-001": {
    ...mockReservations[0],
    hotels: [
      {
        id: "HTL-001",
        reservationId: "RSV-001",
        startDate: "2025-04-15",
        endDate: "2025-04-20",
        city: "Miami",
        hotelName: "Fontainebleau Miami Beach",
        bookingReference: "FB-2025-001",
        totalPrice: 1500,
        amountPaid: 1500,
        roomType: "Ocean View Suite",
        provider: "Booking.com",
        currency: "USD",
      },
    ],
    planes: [
      {
        id: "PLN-001",
        reservationId: "RSV-001",
        departure: "Buenos Aires (EZE)",
        arrival: "Miami (MIA)",
        departureDate: "2025-04-15T08:00:00Z",
        arrivalDate: "2025-04-15T16:30:00Z",
        totalPrice: 1000,
        amountPaid: 1000,
        bookingReference: "AA-123456",
        provider: "American Airlines",
        notes: "2 maletas incluidas",
        currency: "USD",
      },
    ],
    cruises: [],
    transfers: [],
    excursions: [],
    medicalAssists: [],
  },
  "RSV-002": {
    ...mockReservations[1],
    hotels: [],
    planes: [],
    cruises: [],
    transfers: [],
    excursions: [],
    medicalAssists: [],
  },
  "RSV-003": {
    ...mockReservations[2],
    hotels: [],
    planes: [],
    cruises: [],
    transfers: [],
    excursions: [],
    medicalAssists: [],
  },
  "RSV-004": {
    ...mockReservations[3],
    hotels: [],
    planes: [],
    cruises: [],
    transfers: [],
    excursions: [],
    medicalAssists: [],
  },
  "RSV-005": {
    ...mockReservations[4],
    hotels: [],
    planes: [],
    cruises: [],
    transfers: [],
    excursions: [],
    medicalAssists: [],
  },
}
